### ISSUE TITLE
throw new Error(CONST_FILE_NOT_WRITTEN);

### ISSUE THREAD

**Issue by atherdon** [LLazyEmail/generator-module#62]
i think if we wrap it with try - we'll get a better trace next time

```
/workspace/_trying-lit/node_modules/markup-generator/dist/index.cjs.js:2584
    throw new Error(CONST_FILE_NOT_WRITTEN);
          ^

Error: file not written
    at /workspace/_trying-lit/node_modules/markup-generator/dist/index.cjs.js:2584:11
```

**Comment by C-Y-P-H-E-R** [comment]
i am not being able to produce this same error, its working for me.
can you let me know how to reproduce it ?

![Screenshot from 2022-06-20 21-04-45](https://user-images.githubusercontent.com/69472040/174636590-0aac74d0-4057-452d-bd2a-a44079eea531.png)

**Comment by atherdon** [comment]
Thanks for your message and nice to meet you.
This error I get when I called methods from this module in my another
repository

Long story short - when you trying to save data into a file, and passing
empty content wariable - it give you this error.

I'm outside right now, will try to create a better explanation when I get
back to my computer.

**Comment by atherdon** [comment]
So, this issue is throwing an error in this line: https://github.com/LLazyEmail/generator-module/blob/main/src/utils.js#L41

And I was trying to use this module for generating partials for [hackernoon email template](https://github.com/LLazyEmail/_trying-lit). And for some reason, `content` variable is empty, which generates an empty file.
I tried to patch it quickly, but it's still generating an error. If you want, I can record a video and show it to you

cc @C-Y-P-H-E-R

**Comment by atherdon** [comment]
Will do @C-Y-P-H-E-R

**Comment by atherdon** [comment]
https://user-images.githubusercontent.com/1469198/174784384-5c66ecb0-fc4b-4531-b88a-b73df19874cf.mp4

Just recorded a video for you.
Code that you can run is located in this branch: https://github.com/LLazyEmail/_trying-lit/tree/error-in-generator

Thanks!

сс @C-Y-P-H-E-R

**Comment by C-Y-P-H-E-R** [comment]
Hey Arthur!
The error is now resolved as much as i know. (The content is being generated in the form of files in the "generated" folder)
there were a few simple import statements that were missing and were not visible since they lied out of range of our test scripts.
kindly do let me know how would it be best suitable for you get the working code.

here is the #victory image (as i say it lol 🤭)

![Screenshot from 2022-06-25 16-07-51](https://user-images.githubusercontent.com/69472040/175769988-9dfe86a5-dc8f-4fc9-ac6a-59493f09d8f5.png)

hope to hear from you soon buddy!

**Comment by atherdon** [comment]
@C-Y-P-H-E-R WOW! awesome

yeah, i wanna to migrate tests from the main project, but always find an excuse ((

can you submit your changes so I can add them to this repo?

**Comment by C-Y-P-H-E-R** [comment]
yeah.
so i've pushed the fixed code on this repo for you to clone it.
the branch name is "fixed-code"
here is the link.
https://github.com/C-Y-P-H-E-R/email_markup_gen/tree/fixed-code

**Comment by atherdon** [comment]
opening right now - huge thanks!

**Comment by atherdon** [comment]
@C-Y-P-H-E-R did the changes to the main branch on trying_lit
means a lot to me

![xxx](https://media.giphy.com/media/U4DswrBiaz0p67ZweH/giphy.gif)

**Comment by C-Y-P-H-E-R** [comment]
amazing!
done and dusted then! :)
don't forget to close this issue friend, would give me immense satisfaction lol ;)

**Comment by atherdon** [comment]
closing it
